### Pandas 100 Questions

In [88]:
import numpy as np
import pandas as pd

### Q1. Create a Pandas Series from a list of integers.
> 💡 **Hint:** Use `pd.Series([...])`. The default index starts from 0.

In [89]:
series = pd.Series([2,3,5,7,11,13,17,19])
print(series)

0     2
1     3
2     5
3     7
4    11
5    13
6    17
7    19
dtype: int64

### Q2. Create a Series from a dictionary with custom index.
> 💡 **Hint:** Pass a `dict` to `pd.Series()`. Keys become the index labels automatically.

In [90]:

my_dict = {'Apple': 1.20, 'Banana': 0.50, 'Cherry': 2.50}

my_series = pd.Series(my_dict)

print(my_series)

Apple     1.2
Banana    0.5
Cherry    2.5
dtype: float64

### Q3. Access elements using index labels.
> 💡 **Hint:** Use `s["label"]` for a single value, `s[["a","b"]]` for multiple, and `s["a":"c"]` for a range. Label slices are **inclusive** on both ends.

In [91]:
print(my_series['Apple'] )

print(10*'*')

print(my_series[['Apple', 'Banana']] )

print(10*'*')

print(my_series['Apple': 'Cherry'] )

1.2
**********
Apple     1.2
Banana    0.5
dtype: float64
**********
Apple     1.2
Banana    0.5
Cherry    2.5
dtype: float64

### Q4. Perform arithmetic operations on a Series.
> 💡 **Hint:** Use `+`, `-`, `*`, `/`, `//`, `%`, `**` directly on the Series. Operations are **element-wise** and **index-aligned**.

In [92]:
print(series + 10)
print(10*'*')

print(series - 10)
print(10*'*')

print(series * 10)
print(10*'*')

print(series / 10)
print(10*'*')

print(series // 10)
print(10*'*')

print(series % 10)
print(10*'*')

print(series ** 10)
print(10*'*')

0    12
1    13
2    15
3    17
4    21
5    23
6    27
7    29
dtype: int64
**********
0   -8
1   -7
2   -5
3   -3
4    1
5    3
6    7
7    9
dtype: int64
**********
0     20
1     30
2     50
3     70
4    110
5    130
6    170
7    190
dtype: int64
**********
0    0.2
1    0.3
2    0.5
3    0.7
4    1.1
5    1.3
6    1.7
7    1.9
dtype: float64
**********
0    0
1    0
2    0
3    0
4    1
5    1
6    1
7    1
dtype: int64
**********
0    2
1    3
2    5
3    7
4    1
5    3
6    7
7    9
dtype: int64
**********
0             1024
1            59049
2          9765625
3        282475249
4      25937424601
5     137858491849
6    2015993900449
7    6131066257801
dtype: int64
**********

### Q5. Find mean, min, max of a Series.
> 💡 **Hint:** Use `.mean()`, `.min()`, `.max()`, `.sum()`, `.median()`, `.std()` directly on the Series.

In [93]:
series
print('mean',series.mean())
print('min',series.min())
print('max',series.max())
print('sum',series.sum())
print('median',series.median())
print('sd',series.std())

mean 9.625
min 2
max 19
sum 77
median 9.0
sd 6.3905622377288305

### Q6. Apply conditional filtering on a Series.
> 💡 **Hint:** Use a boolean mask: `s[s > 50]`. You can also chain conditions with `&` and `|`.

In [94]:
series[(series>5)&(series <10)]

3    7
dtype: int64

### Q7. Replace values in a Series.
> 💡 **Hint:** Use `.replace(old_val, new_val)` or pass a dictionary `{old: new}` to replace multiple values at once.

In [95]:
series.replace(11,200)

0      2
1      3
2      5
3      7
4    200
5     13
6     17
7     19
dtype: int64

### Q8. Convert Series data type.
> 💡 **Hint:** Use `.astype(dtype)` — e.g., `.astype(int)`, `.astype(float)`, `.astype("category")`.

In [96]:
print(series.dtype)

print(series.astype(int))
series.astype(float)

int64
0     2
1     3
2     5
3     7
4    11
5    13
6    17
7    19
dtype: int32

0     2.0
1     3.0
2     5.0
3     7.0
4    11.0
5    13.0
6    17.0
7    19.0
dtype: float64

### Q9. Check for null values in Series.
> 💡 **Hint:** Use `.isnull()` (returns boolean Series) or `.isnull().sum()` for a count.

In [97]:
series.isnull().sum()

0

### Q10. Fill missing values in Series.
> 💡 **Hint:** Use `.fillna(value)` for constant, `.fillna(s.mean())` for mean, `.ffill()` for forward fill, `.bfill()` for backward fill.

In [98]:
series.astype(float)

series = series.replace(11,np.nan)
print("series with missing value\n", series)

series.fillna(series.mean())
print("forward fill",series.ffill())
print("backword fill",series.bfill())

series with missing value
 0     2.0
1     3.0
2     5.0
3     7.0
4     NaN
5    13.0
6    17.0
7    19.0
dtype: float64
forward fill 0     2.0
1     3.0
2     5.0
3     7.0
4     7.0
5    13.0
6    17.0
7    19.0
dtype: float64
backword fill 0     2.0
1     3.0
2     5.0
3     7.0
4    13.0
5    13.0
6    17.0
7    19.0
dtype: float64

### Q11. Create DataFrame from a list.
> 💡 **Hint:** Use `pd.DataFrame(list_of_lists, columns=[...])`. Each inner list becomes one row.

In [99]:
lists= [[1,'ankit', 8, 'a','pune'],[2,'pulkit', 10, 'b','mumbai'],[3,'sanket', 7, 'c','bengalore'],[4,'ganesh', 8, 'd','pune']]
df_lists = pd.DataFrame(lists,columns=['sr. no', 'name', 'class', 'grade', 'city'])
df_lists

   sr. no    name  class grade       city
0       1   ankit      8     a       pune
1       2  pulkit     10     b     mumbai
2       3  sanket      7     c  bengalore
3       4  ganesh      8     d       pune

### Q12. Create DataFrame from a dictionary.
> 💡 **Hint:** Use `pd.DataFrame({col: values})`. Keys become column names; values must have equal length.

In [100]:
df_dict = pd.DataFrame({
    'Sr. no': [1,2,3,4],
    'name':['ankit', 'pulkit','sanket','ganesh'],
    'class':[8,10,7,8],
    'city':['pune','mumbai','bengalore','pune']   
    })
df_dict

   Sr. no    name  class       city
0       1   ankit      8       pune
1       2  pulkit     10     mumbai
2       3  sanket      7  bengalore
3       4  ganesh      8       pune

### Q13. Create DataFrame from list of dictionaries.
> 💡 **Hint:** Use `pd.DataFrame([{...}, {...}])`. Each dict is a row; missing keys become `NaN`.

In [101]:
pd_ldicts= pd.DataFrame([{'name':'ankit','class':8,'city':'pune'},{'name':'pulkit','city':'mumbai'},{'name':'sanket','class':10}])
pd_ldicts

     name  class    city
0   ankit    8.0    pune
1  pulkit    NaN  mumbai
2  sanket   10.0     NaN

### Q14. Display DataFrame structure (shape, columns, dtypes).
> 💡 **Hint:** Use `df.shape`, `df.columns`, `df.dtypes`, `df.info()`, and `df.describe()`.

In [102]:
print('shape -->',df_lists.shape)
print(30*'*')

print('columns -->',df_lists.columns)
print(30*'*')

print('data type -->',df_lists.dtypes)
print(30*'*')

print('info -->',df_lists.info())
print(30*'*')

print('description -->',df_lists.describe())

shape --> (4, 5)
******************************
columns --> Index(['sr. no', 'name', 'class', 'grade', 'city'], dtype='object')
******************************
data type --> sr. no     int64
name      object
class      int64
grade     object
city      object
dtype: object
******************************
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   sr. no  4 non-null      int64
 1   name    4 non-null      object
 2   class   4 non-null      int64
 3   grade   4 non-null      object
 4   city    4 non-null      object
dtypes: int64(2), object(3)
memory usage: 288.0+ bytes
info --> None
******************************
description -->          sr. no      class
count  4.000000   4.000000
mean   2.500000   8.250000
std    1.290994   1.258306
min    1.000000   7.000000
25%    1.750000   7.750000
50%    2.500000   8.000000
75%    3.250000   8.500000
max    4.000000  10.000000

### Q15. Select single column from DataFrame.
> 💡 **Hint:** Use `df["col_name"]` — this returns a **Series**. You can also use `df.col_name` (dot notation).

In [103]:
df_lists['name']

0     ankit
1    pulkit
2    sanket
3    ganesh
Name: name, dtype: object

### Q16. Select multiple columns.
> 💡 **Hint:** Use `df[["col1", "col2"]]` with a list inside the brackets — this returns a **DataFrame**.

In [104]:
df_lists[['name', 'city']]

     name       city
0   ankit       pune
1  pulkit     mumbai
2  sanket  bengalore
3  ganesh       pune

### Q17. Add new column with scalar value.
> 💡 **Hint:** `df["new_col"] = 10` — the scalar is **broadcast** to all rows automatically.

In [105]:
df_lists['fees paid']= "Yes"
df_lists

   sr. no    name  class grade       city fees paid
0       1   ankit      8     a       pune       Yes
1       2  pulkit     10     b     mumbai       Yes
2       3  sanket      7     c  bengalore       Yes
3       4  ganesh      8     d       pune       Yes

### Q18. Add column using Series.
> 💡 **Hint:** `df["new_col"] = pd.Series([...])`. The Series index must align with the DataFrame index.

In [106]:
df_lists['scores']= pd.Series([98,90,89,81])
df_lists

   sr. no    name  class grade       city fees paid  scores
0       1   ankit      8     a       pune       Yes      98
1       2  pulkit     10     b     mumbai       Yes      90
2       3  sanket      7     c  bengalore       Yes      89
3       4  ganesh      8     d       pune       Yes      81

### Q19. Rename columns using `rename()`.
> 💡 **Hint:** Use `df.rename(columns={"old": "new"})`. Add `inplace=True` to modify in-place.

In [107]:
df_lists.rename(columns={'grade':'grades'}, inplace=True)
df_lists

   sr. no    name  class grades       city fees paid  scores
0       1   ankit      8      a       pune       Yes      98
1       2  pulkit     10      b     mumbai       Yes      90
2       3  sanket      7      c  bengalore       Yes      89
3       4  ganesh      8      d       pune       Yes      81

### Q20. Rename multiple columns.
> 💡 **Hint:** Pass a dictionary with multiple key-value pairs to `rename(columns={...})`.

In [108]:
df_lists.rename(columns={'grades':'grade', 'city':'location'}, inplace=True)
df_lists

   sr. no    name  class grade   location fees paid  scores
0       1   ankit      8     a       pune       Yes      98
1       2  pulkit     10     b     mumbai       Yes      90
2       3  sanket      7     c  bengalore       Yes      89
3       4  ganesh      8     d       pune       Yes      81

### Q21. Select rows using `loc`.
> 💡 **Hint:** `df.loc[label]` for a single row, `df.loc[label1:label2]` for a range. **Inclusive on both ends.**

In [109]:
df_lists.loc[[1,3]]
df_lists.loc[1:3]

   sr. no    name  class grade   location fees paid  scores
1       2  pulkit     10     b     mumbai       Yes      90
2       3  sanket      7     c  bengalore       Yes      89
3       4  ganesh      8     d       pune       Yes      81

### Q22. Select rows using `iloc`.
> 💡 **Hint:** `df.iloc[0]` for first row, `df.iloc[1:4]` for rows 1–3. **Exclusive on the end** (Python-style).

In [110]:
df_lists.iloc[0]
df_lists.iloc[1:4]

   sr. no    name  class grade   location fees paid  scores
1       2  pulkit     10     b     mumbai       Yes      90
2       3  sanket      7     c  bengalore       Yes      89
3       4  ganesh      8     d       pune       Yes      81

### Q23. Access specific row and column.
> 💡 **Hint:** `df.loc[row_label, "col_name"]` or `df.iloc[row_pos, col_pos]` for a single cell.

In [111]:
df_lists.loc[2,'location']

'bengalore'

### Q24. Select subset using multiple rows & columns.
> 💡 **Hint:** `df.loc[[r1,r2], ["col1","col2"]]` or `df.iloc[[0,1], [0,2]]`.

In [112]:
df_lists.iloc[[0,1],[0,2]]
df_lists.loc[[0,1],['name','class']]

     name  class
0   ankit      8
1  pulkit     10

### Q25. Apply conditional filtering using `loc`.
> 💡 **Hint:** `df.loc[df["col"] > value, ["col1","col2"]]` — pass a boolean Series as the row selector.

In [113]:
df_lists.loc[df_lists['scores']>85]

   sr. no    name  class grade   location fees paid  scores
0       1   ankit      8     a       pune       Yes      98
1       2  pulkit     10     b     mumbai       Yes      90
2       3  sanket      7     c  bengalore       Yes      89

### Q26. Slice rows using index range.
> 💡 **Hint:** Use `df.iloc[start:end]` for position-based slicing or `df.loc[label1:label2]` for label-based slicing.

In [114]:
df_lists.iloc[2:4]
df_lists.loc[:2] #here we talk abour defalut labels - 0,1,2,3

   sr. no    name  class grade   location fees paid  scores
0       1   ankit      8     a       pune       Yes      98
1       2  pulkit     10     b     mumbai       Yes      90
2       3  sanket      7     c  bengalore       Yes      89

### Q27. Slice columns using labels.
> 💡 **Hint:** `df.loc[:, "col1":"col3"]` — selects all rows, columns from col1 to col3 (label-inclusive).

In [115]:
df_lists.loc[:2,'name':'location']

     name  class grade   location
0   ankit      8     a       pune
1  pulkit     10     b     mumbai
2  sanket      7     c  bengalore

### Q28. Slice columns using position.
> 💡 **Hint:** `df.iloc[:, 1:4]` — selects all rows, columns at positions 1, 2, 3.

In [116]:
df_lists.iloc[:,:2]

   sr. no    name
0       1   ankit
1       2  pulkit
2       3  sanket
3       4  ganesh

### Q29. Perform combined row & column slicing.
> 💡 **Hint:** `df.loc[row_condition, ["col1","col2"]]` or `df.iloc[0:5, [0, 2, 4]]`.

In [117]:
df_lists.iloc[1:4,[2,3,5]] 
df_lists.loc[1:4,['name', 'scores', 'location']]

     name  scores   location
1  pulkit      90     mumbai
2  sanket      89  bengalore
3  ganesh      81       pune

### Q30. Set a column as index.
> 💡 **Hint:** Use `df.set_index("col_name")`. Add `inplace=True` to modify without reassigning.

In [118]:
df_lists.set_index('sr. no')

          name  class grade   location fees paid  scores
sr. no
1        ankit      8     a       pune       Yes      98
2       pulkit     10     b     mumbai       Yes      90
3       sanket      7     c  bengalore       Yes      89
4       ganesh      8     d       pune       Yes      81

### Q31. Create hierarchical index (MultiIndex).
> 💡 **Hint:** `df.set_index(["col1","col2"])` — pass a **list** of column names to create a MultiIndex.

In [119]:
df_lists.set_index(['sr. no','name'], inplace=True)

In [120]:
df_lists

               class grade   location fees paid  scores
sr. no name
1      ankit       8     a       pune       Yes      98
2      pulkit     10     b     mumbai       Yes      90
3      sanket      7     c  bengalore       Yes      89
4      ganesh      8     d       pune       Yes      81

### Q32. Reset index.
> 💡 **Hint:** `df.reset_index()` — moves the current index back to a column. Use `inplace=True` to modify in-place.

In [121]:
df_lists.reset_index(inplace=True)

In [122]:
df_lists

   sr. no    name  class grade   location fees paid  scores
0       1   ankit      8     a       pune       Yes      98
1       2  pulkit     10     b     mumbai       Yes      90
2       3  sanket      7     c  bengalore       Yes      89
3       4  ganesh      8     d       pune       Yes      81

### Q33. Reset multi-index.
> 💡 **Hint:** `df.reset_index()` on a MultiIndex DataFrame flattens both index levels back to columns.

In [123]:
df_lists.set_index(['sr. no','name'], inplace=True)
df_lists.reset_index(inplace=True)

In [124]:
df_lists

   sr. no    name  class grade   location fees paid  scores
0       1   ankit      8     a       pune       Yes      98
1       2  pulkit     10     b     mumbai       Yes      90
2       3  sanket      7     c  bengalore       Yes      89
3       4  ganesh      8     d       pune       Yes      81

### Q34. Convert index to column.
> 💡 **Hint:** `df.reset_index()` by default moves the index to a column. Use `drop=False` (default) to keep it.

In [125]:
df_lists.reset_index(drop=False)

   index  sr. no    name  class grade   location fees paid  scores
0      0       1   ankit      8     a       pune       Yes      98
1      1       2  pulkit     10     b     mumbai       Yes      90
2      2       3  sanket      7     c  bengalore       Yes      89
3      3       4  ganesh      8     d       pune       Yes      81

### Q35. Use drop option in `reset_index`.
> 💡 **Hint:** `df.reset_index(drop=True)` discards the old index completely instead of converting it to a column.

In [126]:
df_lists.reset_index(drop=True)

   sr. no    name  class grade   location fees paid  scores
0       1   ankit      8     a       pune       Yes      98
1       2  pulkit     10     b     mumbai       Yes      90
2       3  sanket      7     c  bengalore       Yes      89
3       4  ganesh      8     d       pune       Yes      81

### Q36. Perform label-based indexing.
> 💡 **Hint:** Use `df.loc[label]` — works with any index type (string, integer, datetime labels).

In [127]:
df_lists.set_index('name', inplace=True)

In [128]:
df_lists.loc[['ankit', 'pulkit']]

        sr. no  class grade location fees paid  scores
name
ankit        1      8     a     pune       Yes      98
pulkit       2     10     b   mumbai       Yes      90

### Q37. Perform position-based indexing.
> 💡 **Hint:** Use `df.iloc[0]` — always integer-based, regardless of the index type.

In [129]:
df_lists.iloc[[0,3]]

        sr. no  class grade location fees paid  scores
name
ankit        1      8     a     pune       Yes      98
ganesh       4      8     d     pune       Yes      81

### Q38. Access first N rows.
> 💡 **Hint:** `df.head(N)` — default N is 5.

In [130]:
df_lists.head(2)

        sr. no  class grade location fees paid  scores
name
ankit        1      8     a     pune       Yes      98
pulkit       2     10     b   mumbai       Yes      90

### Q39. Access last N rows.
> 💡 **Hint:** `df.tail(N)` — default N is 5.

In [131]:
df_lists.tail(2)

        sr. no  class grade   location fees paid  scores
name
sanket       3      7     c  bengalore       Yes      89
ganesh       4      8     d       pune       Yes      81

### Q40. Extract random sample from DataFrame.
> 💡 **Hint:** `df.sample(n=5)` for random rows, `df.sample(frac=0.2)` for 20% of rows. Set `random_state` for reproducibility.

In [132]:
df_lists.sample(2)

        sr. no  class grade location fees paid  scores
name
pulkit       2     10     b   mumbai       Yes      90
ganesh       4      8     d     pune       Yes      81

## 🔹 Section 3: Data Cleaning (Q41–Q60)

---

In [133]:
lists= [[1,'ankit', np.nan, 'a','pune'],[2,'pulkit', 10, 'b','mumbai'],[3,'sanket', 7, 'c','bengalore'],[4,'ganesh', 8, 'd','pune'],[5,'suraj', np.nan, 'a','khandala'],[1,'antu', 10, 'a','pune']]
df = pd.DataFrame(lists,columns=['sr. no', 'name', 'class', 'grade', 'city'])


df['scores']= pd.Series([98,np.nan,50,np.nan, 82])
df

   sr. no    name  class grade       city  scores
0       1   ankit    NaN     a       pune    98.0
1       2  pulkit   10.0     b     mumbai     NaN
2       3  sanket    7.0     c  bengalore    50.0
3       4  ganesh    8.0     d       pune     NaN
4       5   suraj    NaN     a   khandala    82.0
5       1    antu   10.0     a       pune     NaN

### Q41. Detect missing values using `isnull()`.
> 💡 **Hint:** `df.isnull()` returns a boolean DataFrame. Use `.isnull().sum()` for column-wise counts or `.isnull().any()` to check if any exist.

In [134]:
print(df.isnull().any())
df.isnull().sum()

sr. no    False
name      False
class      True
grade     False
city      False
scores     True
dtype: bool

sr. no    0
name      0
class     2
grade     0
city      0
scores    3
dtype: int64

### Q42. Drop missing values using `dropna()`.
> 💡 **Hint:** `df.dropna()` drops any row with a NaN. Use `axis=1` for columns, `subset=["col"]` for specific columns, and `thresh=N` to keep rows with at least N non-null values.

In [135]:
df.dropna()

   sr. no    name  class grade       city  scores
2       3  sanket    7.0     c  bengalore    50.0

In [136]:
df.dropna(axis=1)

   sr. no    name grade       city
0       1   ankit     a       pune
1       2  pulkit     b     mumbai
2       3  sanket     c  bengalore
3       4  ganesh     d       pune
4       5   suraj     a   khandala
5       1    antu     a       pune

### Q43. Fill missing values with a constant.
> 💡 **Hint:** `df.fillna(0)` or `df["col"].fillna("Unknown")`. You can also pass a dict to fill different columns with different values.

In [137]:
df.fillna(0)

   sr. no    name  class grade       city  scores
0       1   ankit    0.0     a       pune    98.0
1       2  pulkit   10.0     b     mumbai     0.0
2       3  sanket    7.0     c  bengalore    50.0
3       4  ganesh    8.0     d       pune     0.0
4       5   suraj    0.0     a   khandala    82.0
5       1    antu   10.0     a       pune     0.0

In [138]:
df['scores'].fillna(40)

0    98.0
1    40.0
2    50.0
3    40.0
4    82.0
5    40.0
Name: scores, dtype: float64

### Q44. Fill missing values using mean/median.
> 💡 **Hint:** `df["col"].fillna(df["col"].mean())` or `df["col"].fillna(df["col"].median())`.

In [139]:
df['scores'].fillna(df['scores'].mean())

0    98.000000
1    76.666667
2    50.000000
3    76.666667
4    82.000000
5    76.666667
Name: scores, dtype: float64

In [140]:
df['scores'].fillna(df['scores'].median())

0    98.0
1    82.0
2    50.0
3    82.0
4    82.0
5    82.0
Name: scores, dtype: float64

### Q45. Use forward fill and backward fill.
> 💡 **Hint:** `df.ffill()` propagates the last valid value forward. `df.bfill()` fills using the next valid value.

In [141]:
df.ffill()

   sr. no    name  class grade       city  scores
0       1   ankit    NaN     a       pune    98.0
1       2  pulkit   10.0     b     mumbai    98.0
2       3  sanket    7.0     c  bengalore    50.0
3       4  ganesh    8.0     d       pune    50.0
4       5   suraj    8.0     a   khandala    82.0
5       1    antu   10.0     a       pune    82.0

In [142]:
df.bfill()

   sr. no    name  class grade       city  scores
0       1   ankit   10.0     a       pune    98.0
1       2  pulkit   10.0     b     mumbai    50.0
2       3  sanket    7.0     c  bengalore    50.0
3       4  ganesh    8.0     d       pune    82.0
4       5   suraj   10.0     a   khandala    82.0
5       1    antu   10.0     a       pune     NaN

### Q46. Convert data type using `astype()`.
> 💡 **Hint:** `df["col"].astype(int)` or `df["col"].astype("category")`. Use `errors="coerce"` inside `pd.to_numeric()` to handle invalid values.

In [143]:
df['sr. no'].astype(int)

0    1
1    2
2    3
3    4
4    5
5    1
Name: sr. no, dtype: int32

### Q47. Clean string column using `.str.lower()`.
> 💡 **Hint:** Access the `.str` accessor first: `df["col"].str.lower()`. Similarly `.str.upper()`, `.str.title()`.

In [144]:
df['name'].str.upper()

0     ANKIT
1    PULKIT
2    SANKET
3    GANESH
4     SURAJ
5      ANTU
Name: name, dtype: object

In [145]:
df['name'].str.title()

0     Ankit
1    Pulkit
2    Sanket
3    Ganesh
4     Suraj
5      Antu
Name: name, dtype: object

### Q48. Trim whitespace in strings.
> 💡 **Hint:** `df["col"].str.strip()` removes leading and trailing spaces. Use `.str.lstrip()` / `.str.rstrip()` for one side.

In [146]:
df['name'].str.strip()

0     ankit
1    pulkit
2    sanket
3    ganesh
4     suraj
5      antu
Name: name, dtype: object

### Q49. Replace substring in column.
> 💡 **Hint:** `df["col"].str.replace("old", "new")`. Add `regex=True` for pattern-based replacement.

In [147]:
df['city'].str.replace('pune','Pune')

0         Pune
1       mumbai
2    bengalore
3         Pune
4     khandala
5         Pune
Name: city, dtype: object

### Q50. Extract part of string using `.str`.
> 💡 **Hint:** `df["col"].str[:3]` for first 3 chars. Use `.str.split("@").str[1]` to extract after a delimiter.

In [148]:
df['city'].str[:3]

0    pun
1    mum
2    ben
3    pun
4    kha
5    pun
Name: city, dtype: object

In [149]:
df['city'].str.split("@").str[1]

0   NaN
1   NaN
2   NaN
3   NaN
4   NaN
5   NaN
Name: city, dtype: float64

In [150]:
df

   sr. no    name  class grade       city  scores
0       1   ankit    NaN     a       pune    98.0
1       2  pulkit   10.0     b     mumbai     NaN
2       3  sanket    7.0     c  bengalore    50.0
3       4  ganesh    8.0     d       pune     NaN
4       5   suraj    NaN     a   khandala    82.0
5       1    antu   10.0     a       pune     NaN

### Q51. Detect duplicate rows.
> 💡 **Hint:** `df.duplicated()` returns a boolean Series. Use `df[df.duplicated()]` to see the actual duplicate rows.

In [151]:
df[df.duplicated()]

Empty DataFrame
Columns: [sr. no, name, class, grade, city, scores]
Index: []

### Q52. Remove duplicates using `drop_duplicates()`.
> 💡 **Hint:** `df.drop_duplicates()` keeps the first occurrence by default. Use `subset=["col"]` to check specific columns, and `keep="last"` or `keep=False`.

In [152]:
df.drop_duplicates(subset=['city'])

   sr. no    name  class grade       city  scores
0       1   ankit    NaN     a       pune    98.0
1       2  pulkit   10.0     b     mumbai     NaN
2       3  sanket    7.0     c  bengalore    50.0
4       5   suraj    NaN     a   khandala    82.0

### Q53. Rename row labels.
> 💡 **Hint:** `df.rename(index={old_label: new_label})`.

In [153]:
df1 = pd.DataFrame({'A': [10, 20], 'B': [30, 40]}, index=['row1', 'row2'])
df1.rename(index={'row1' :'r1'})

       A   B
r1    10  30
row2  20  40

### Q54. Handle inconsistent data.
> 💡 **Hint:** Use `.str.strip().str.lower()` to normalize strings. Use `.replace({...})` to map inconsistent values to a standard form.

In [154]:
df2 = pd.DataFrame({
    'id': [1, 2, 3, 4, 5],
    'area': ['Pune', 'pun ', 'pune  ', 'PUNE', ' poona']
})
df2

df2['area'].str.strip().str.lower().replace({'pun':'pune','poona':'pune'})

0    pune
1    pune
2    pune
3    pune
4    pune
Name: area, dtype: object

### Q55. Replace values in DataFrame.
> 💡 **Hint:** `df.replace("old", "new")` works DataFrame-wide. Pass a dict `{old: new}` or nested dict `{"col": {old: new}}` for column-specific replacement.

In [155]:
df.replace('ankit','aniket')

   sr. no    name  class grade       city  scores
0       1  aniket    NaN     a       pune    98.0
1       2  pulkit   10.0     b     mumbai     NaN
2       3  sanket    7.0     c  bengalore    50.0
3       4  ganesh    8.0     d       pune     NaN
4       5   suraj    NaN     a   khandala    82.0
5       1    antu   10.0     a       pune     NaN

### Q56. Detect outliers in a column.
> 💡 **Hint:** Use the **IQR method**: compute Q1, Q3, IQR = Q3–Q1. Outliers are values below `Q1 - 1.5*IQR` or above `Q3 + 1.5*IQR`. Alternatively use Z-score: `|z| > 3`.

In [156]:
df3 = pd.DataFrame({
    'id': [1, 2, 3, 4, 5],
    'prices': [200, 400, 350, 20000,10]
})
df3

   id  prices
0   1     200
1   2     400
2   3     350
3   4   20000
4   5      10

In [157]:
q1 = df3['prices'].quantile(0.25)
q3 = df3['prices'].quantile(0.75)
iqr = q3-q1
iqr

low_limit = q1 - 1.5*iqr
up_limit = q3 + 1.5*iqr

df3[(df3['prices']> up_limit) |(df3['prices']< low_limit)]

   id  prices
3   4   20000

### Q57. Handle outliers using clipping.
> 💡 **Hint:** `df["col"].clip(lower=lo, upper=hi)` replaces values outside the bounds with the boundary values.

In [158]:
df3['prices'].clip(300,500)

0    300
1    400
2    350
3    500
4    300
Name: prices, dtype: int64

### Q58. Standardize column names.
> 💡 **Hint:** `df.columns = df.columns.str.strip().str.lower().str.replace(" ", "_")` — clean all column names in one line.

In [159]:
df.columns.str.strip().str.lower().str.replace('sr.no','id')

C:\Users\abc\AppData\Local\Temp/ipykernel_19860/422556595.py:1: FutureWarning: The default value of regex will change from True to False in a future version.
  df.columns.str.strip().str.lower().str.replace('sr.no','id')

Index(['sr. no', 'name', 'class', 'grade', 'city', 'scores'], dtype='object')

### Q59. Handle mixed data types in a column.
> 💡 **Hint:** Use `pd.to_numeric(df["col"], errors="coerce")` to convert to numbers, turning invalid strings into `NaN`.

In [160]:
df3['others']= pd.Series([23,34,'aslam',90,'$'])
df3

   id  prices others
0   1     200     23
1   2     400     34
2   3     350  aslam
3   4   20000     90
4   5      10      $

In [161]:
pd.to_numeric(df3['others'], errors='coerce')

0    23.0
1    34.0
2     NaN
3    90.0
4     NaN
Name: others, dtype: float64

### Q60. Remove special characters from text data.
> 💡 **Hint:** `df["col"].str.replace(r"[^a-zA-Z0-9 ]", "", regex=True)` — use regex to keep only alphanumeric characters.

In [162]:
df3['others'].str.replace(r"[^a-zA-Z0-9 ]", "", regex=True)

0      NaN
1      NaN
2    aslam
3      NaN
4
Name: others, dtype: object


## 🔹 Section 4: Data Manipulation (Q61–Q80)

---

### Q61. Filter rows using AND condition.
> 💡 **Hint:** `df[(df["col1"] > val) & (df["col2"] == "x")]` — wrap each condition in parentheses and use `&`.

In [163]:
df3[(df3['prices']>200) & (df3['prices']<1000)]

   id  prices others
1   2     400     34
2   3     350  aslam

### Q62. Filter rows using OR condition.
> 💡 **Hint:** `df[(df["col1"] > val) | (df["col2"] == "x")]` — use `|` between conditions.

In [164]:
df3[(df3['prices']<200) | (df3['prices']>1000)]

   id  prices others
3   4   20000     90
4   5      10      $

### Q63. Filter rows using NOT condition.
> 💡 **Hint:** `df[~(df["col"] == "val")]` — use `~` to negate a boolean condition.

In [165]:
df3[~(df3['prices']==400)] #price not equal to 400

   id  prices others
0   1     200     23
2   3     350  aslam
3   4   20000     90
4   5      10      $

### Q64. Sort DataFrame by column values.
> 💡 **Hint:** `df.sort_values("col")`. Use `ascending=False` for descending, `by=["col1","col2"]` for multi-column sort.

In [166]:
df3.sort_values('prices')

   id  prices others
4   5      10      $
0   1     200     23
2   3     350  aslam
1   2     400     34
3   4   20000     90

In [167]:
df.sort_values(['city','name'],ascending=[False,True]) # multiple column and customised

   sr. no    name  class grade       city  scores
0       1   ankit    NaN     a       pune    98.0
5       1    antu   10.0     a       pune     NaN
3       4  ganesh    8.0     d       pune     NaN
1       2  pulkit   10.0     b     mumbai     NaN
4       5   suraj    NaN     a   khandala    82.0
2       3  sanket    7.0     c  bengalore    50.0

### Q65. Sort DataFrame by index.
> 💡 **Hint:** `df.sort_index()`. Use `axis=1` to sort columns alphabetically.

In [168]:
df.sort_index(axis=1)

        city  class grade    name  scores  sr. no
0       pune    NaN     a   ankit    98.0       1
1     mumbai   10.0     b  pulkit     NaN       2
2  bengalore    7.0     c  sanket    50.0       3
3       pune    8.0     d  ganesh     NaN       4
4   khandala    NaN     a   suraj    82.0       5
5       pune   10.0     a    antu     NaN       1

### Q66. Add calculated column.
> 💡 **Hint:** `df["new"] = df["col1"] * df["col2"]` or use `.assign(new=lambda x: ...)` for chainable operations.

In [169]:
df1['sum']= df1['A']+ df1['B']
df1

       A   B  sum
row1  10  30   40
row2  20  40   60

### Q67. Remove column using `drop()`.
> 💡 **Hint:** `df.drop(columns=["col1","col2"])`. Always use the `columns=` parameter to be explicit.

In [170]:
df1.drop(columns=['sum'])

       A   B
row1  10  30
row2  20  40

### Q68. Remove rows using `drop()`.
> 💡 **Hint:** `df.drop(index=[0, 3])` removes rows with those index labels.

In [171]:
df2.drop(index=[1,4])

   id    area
0   1    Pune
2   3  pune
3   4    PUNE

### Q69. Use `map()` on a column.
> 💡 **Hint:** `df["col"].map({"a": 1, "b": 2})` substitutes values using a dict. Pass a function for element-wise transformation.

In [172]:
df2['area'],map({})

TypeError: map() must have at least two arguments.

### Q70. Apply function using `apply()`.
> 💡 **Hint:** `df["col"].apply(func)` for a Series. `df.apply(func, axis=0)` column-wise, `df.apply(func, axis=1)` row-wise.

In [ ]:
def square(n):
    return n**2

df1['A'].apply(square)

row1    100
row2    400
Name: A, dtype: int64

In [ ]:
df1

       A   B  sum
row1  10  30   40
row2  20  40   60

### Q71. Apply element-wise using `applymap()` / `map()`.
> 💡 **Hint:** In older pandas use `df.applymap(func)`. In pandas ≥ 2.1 use `df.map(func)` for element-wise operations on the entire DataFrame.

In [ ]:
df1['A'].map(square)

row1    100
row2    400
Name: A, dtype: int64

### Q72. Chain multiple operations.
> 💡 **Hint:** Use method chaining with `(df.copy().loc[...].sort_values(...)[cols].assign(...).reset_index(drop=True))` — wrap in parentheses for multi-line readability.

In [ ]:
print(df.copy().loc[0:4].sort_values('grade')[['name', 'grade']].reset_index(drop = True))

     name grade
0   ankit     a
1   suraj     a
2  pulkit     b
3  sanket     c
4  ganesh     d

### Q73. Normalize numeric columns (Min-Max).
> 💡 **Hint:** `(df["col"] - df["col"].min()) / (df["col"].max() - df["col"].min())` — result is in range [0, 1].

In [ ]:
(df3["prices"] - df3["prices"].min()) / (df3["prices"].max() - df3["prices"].min()) #X-Xmin/Xmax-Xmin

0    0.009505
1    0.019510
2    0.017009
3    1.000000
4    0.000000
Name: prices, dtype: float64

In [ ]:
df3

   id  prices others
0   1     200     23
1   2     400     34
2   3     350  aslam
3   4   20000     90
4   5      10      $

### Q74. Scale numerical data (Z-score standardization).
> 💡 **Hint:** `(df["col"] - df["col"].mean()) / df["col"].std()` — result has mean=0 and std=1.

In [ ]:
(df1["A"] - df1["A"].mean()) / df1["A"].std()

row1   -0.707107
row2    0.707107
Name: A, dtype: float64

### Q75. Rank values in a column.
> 💡 **Hint:** `df["col"].rank()` — use `ascending=False` for descending rank, `method="dense"` to avoid gaps.

In [ ]:
df3['rank']= df3['prices'].rank(ascending=False)

In [ ]:
df3

   id  prices others  rank
0   1     200     23   4.0
1   2     400     34   2.0
2   3     350  aslam   3.0
3   4   20000     90   1.0
4   5      10      $   5.0

### Q76. Create bins using `cut()`.
> 💡 **Hint:** `pd.cut(df["col"], bins=4)` for equal-width bins or `pd.cut(df["col"], bins=[0,25,50,75,100], labels=["Low","Mid","High","Top"])` for custom intervals.

In [ ]:
pd.cut(df3['prices'], bins= 4)

0       (-9.99, 5007.5]
1       (-9.99, 5007.5]
2       (-9.99, 5007.5]
3    (15002.5, 20000.0]
4       (-9.99, 5007.5]
Name: prices, dtype: category
Categories (4, interval[float64, right]): [(-9.99, 5007.5] < (5007.5, 10005.0] < (10005.0, 15002.5] < (15002.5, 20000.0]]

### Q77. Create bins using `qcut()`.
> 💡 **Hint:** `pd.qcut(df["col"], q=4)` for **equal-frequency** (quantile-based) bins. Use `labels=["Q1","Q2","Q3","Q4"]` for named bins.

In [ ]:
pd.qcut(df3['prices'], q= 4)

0      (9.999, 200.0]
1      (350.0, 400.0]
2      (200.0, 350.0]
3    (400.0, 20000.0]
4      (9.999, 200.0]
Name: prices, dtype: category
Categories (4, interval[float64, right]): [(9.999, 200.0] < (200.0, 350.0] < (350.0, 400.0] < (400.0, 20000.0]]

### Q78. Count unique values.
> 💡 **Hint:** `df["col"].nunique()` for the count, `df["col"].value_counts()` for frequency per unique value.

In [ ]:
df['name'].nunique()

6

In [ ]:
df['city'].value_counts()

pune         3
mumbai       1
bengalore    1
khandala     1
Name: city, dtype: int64

### Q79. Replace multiple values at once.
> 💡 **Hint:** `df.replace({"col": {"old1": "new1", "old2": "new2"}})` or use a list: `df.replace(["old1","old2"], "new")`.

In [ ]:
df.replace({'name':{'antu':'antariksha', 'ganesh':'Aslam'}})

   sr. no        name  class grade       city  scores
0       1       ankit    NaN     a       pune    98.0
1       2      pulkit   10.0     b     mumbai     NaN
2       3      sanket    7.0     c  bengalore    50.0
3       4       Aslam    8.0     d       pune     NaN
4       5       suraj    NaN     a   khandala    82.0
5       1  antariksha   10.0     a       pune     NaN

### Q80. Create flag column based on condition.
> 💡 **Hint:** `df["flag"] = (df["col"] > threshold).astype(int)` — converts True/False to 1/0. Or use `np.where(condition, 1, 0)`.

In [ ]:
df3['flag']= (df3['prices']> 300).astype(int)
df3

   id  prices others  flag
0   1     200     23     0
1   2     400     34     1
2   3     350  aslam     1
3   4   20000     90     1
4   5      10      $     0

## 🔹 Section 5: Iteration, GroupBy & Pivot (Q81–Q100)

---

### Q81. Iterate over rows using `iterrows()`.
> 💡 **Hint:** `for idx, row in df.iterrows():` — `idx` is the index label, `row` is a Series with column values.

In [ ]:
for index, row in df.iterrows():
    print('index->',index,'name->',row['name'],'city->',row['city'])

index-> 0 name-> ankit city-> pune
index-> 1 name-> pulkit city-> mumbai
index-> 2 name-> sanket city-> bengalore
index-> 3 name-> ganesh city-> pune
index-> 4 name-> suraj city-> khandala
index-> 5 name-> antu city-> pune

### Q82. Iterate using `itertuples()`.
> 💡 **Hint:** `for row in df.itertuples():` — `row.col_name` accesses values. **Faster** than `iterrows()` due to named tuples.

In [ ]:
for row in df.itertuples():
    print('name->',row.name,'city->',row.city)

name-> ankit city-> pune
name-> pulkit city-> mumbai
name-> sanket city-> bengalore
name-> ganesh city-> pune
name-> suraj city-> khandala
name-> antu city-> pune

### Q83. Iterate over columns.
> 💡 **Hint:** `for col in df.columns:` then access `df[col]`. Or use `df.items()` which yields `(col_name, Series)` pairs.

In [ ]:
for col in df.columns:
    print(f"Column Name: {col}")
    print(df[col])

Column Name: sr. no
0    1
1    2
2    3
3    4
4    5
5    1
Name: sr. no, dtype: int64
Column Name: name
0     ankit
1    pulkit
2    sanket
3    ganesh
4     suraj
5      antu
Name: name, dtype: object
Column Name: class
0     NaN
1    10.0
2     7.0
3     8.0
4     NaN
5    10.0
Name: class, dtype: float64
Column Name: grade
0    a
1    b
2    c
3    d
4    a
5    a
Name: grade, dtype: object
Column Name: city
0         pune
1       mumbai
2    bengalore
3         pune
4     khandala
5         pune
Name: city, dtype: object
Column Name: scores
0    98.0
1     NaN
2    50.0
3     NaN
4    82.0
5     NaN
Name: scores, dtype: float64

### Q84. Avoid iteration using vectorization.
> 💡 **Hint:** Replace `for` loops with direct column operations: `df["new"] = df["a"] * 2 + 1` instead of a loop over rows.

In [ ]:
df3['evaluation']= df3['prices']*(2+1)

In [ ]:
df

   sr. no    name  class grade       city  scores
0       1   ankit    NaN     a       pune    98.0
1       2  pulkit   10.0     b     mumbai     NaN
2       3  sanket    7.0     c  bengalore    50.0
3       4  ganesh    8.0     d       pune     NaN
4       5   suraj    NaN     a   khandala    82.0
5       1    antu   10.0     a       pune     NaN

### Q85. Group data using `groupby()`.
> 💡 **Hint:** `df.groupby("col")["value_col"].mean()` — specify the grouping key and the aggregation in one line.

In [ ]:
df.groupby('city')['scores'].mean()

city
bengalore    50.0
khandala     82.0
mumbai        NaN
pune         98.0
Name: scores, dtype: float64

### Q86. Calculate sum per group.
> 💡 **Hint:** `df.groupby("col")["value"].sum()` — replace `sum` with any aggregation function.

In [ ]:
df.groupby('city')['scores'].sum()

city
bengalore    50.0
khandala     82.0
mumbai        0.0
pune         98.0
Name: scores, dtype: float64

### Q87. Calculate multiple aggregations.
> 💡 **Hint:** `df.groupby("col").agg({"col1": "mean", "col2": "sum"})` or `df.groupby("col").agg(name=("col","func"))` for named aggregation.

In [ ]:
df.groupby('city').agg({'class':'mean', 'scores':'sum'})

           class  scores
city
bengalore    7.0    50.0
khandala     NaN    82.0
mumbai      10.0     0.0
pune         9.0    98.0

### Q88. Group by multiple columns.
> 💡 **Hint:** `df.groupby(["col1","col2"])["value"].mean()` — pass a list of column names.

In [ ]:
df.groupby(['class','scores'])['scores'].mean()

class  scores
7.0    50.0      50.0
Name: scores, dtype: float64

### Q89. Filter grouped data.
> 💡 **Hint:** `df.groupby("col").filter(lambda g: g["value"].mean() > threshold)` — keeps entire groups satisfying the condition.

In [ ]:
df.groupby('city').filter(lambda x:x['scores'].mean()> 20)

   sr. no    name  class grade       city  scores
0       1   ankit    NaN     a       pune    98.0
2       3  sanket    7.0     c  bengalore    50.0
3       4  ganesh    8.0     d       pune     NaN
4       5   suraj    NaN     a   khandala    82.0
5       1    antu   10.0     a       pune     NaN

### Q90. Transform grouped data using `transform()`.
> 💡 **Hint:** `df.groupby("col")["value"].transform("mean")` — returns a Series **same size as the original DataFrame** filled with group

In [ ]:
df.groupby('city')['scores'].transform('mean')

0    98.0
1     NaN
2    50.0
3    98.0
4    82.0
5    98.0
Name: scores, dtype: float64

### Statistics.

---

### Q91. Apply custom function in groupby.
> 💡 **Hint:** `df.groupby("col")["value"].agg(lambda s: s.max() - s.min())` — pass any function that takes a Series and returns a scalar.

In [ ]:
df.groupby('city')['scores'].agg(lambda x:x.max()-x.min())

city
bengalore    0.0
khandala     0.0
mumbai       NaN
pune         0.0
Name: scores, dtype: float64

### Q92. Create basic pivot table.
> 💡 **Hint:** `pd.pivot_table(df, values="val", index="row_col", columns="col_col", aggfunc="mean")`.

In [ ]:
pd.pivot_table(df,values= 'scores', index = 'name', columns = 'city', aggfunc ='mean')

city    bengalore  khandala  pune
name
ankit         NaN       NaN  98.0
sanket       50.0       NaN   NaN
suraj         NaN      82.0   NaN

### Q93. Use multiple aggregation functions in pivot.
> 💡 **Hint:** Pass a list to `aggfunc`: `aggfunc=["mean","max"]` — the result will have a MultiLevel column header.

In [ ]:
pd.pivot_table(df,values= 'scores', index = 'name', columns = 'city', aggfunc=["mean","max"])

            mean                      max
city   bengalore khandala  pune bengalore khandala  pune
name
ankit        NaN      NaN  98.0       NaN      NaN  98.0
sanket      50.0      NaN   NaN      50.0      NaN   NaN
suraj        NaN     82.0   NaN       NaN     82.0   NaN

### Q94. Handle missing values in pivot tables.
> 💡 **Hint:** Use `fill_value=0` in `pivot_table()` to replace NaN with a specific value.

In [ ]:
pd.pivot_table(df,values= 'scores', index = 'name', columns = 'city', aggfunc=["mean","max"], fill_value=0)

            mean                     max
city   bengalore khandala pune bengalore khandala pune
name
ankit          0        0   98         0        0   98
sanket        50        0    0        50        0    0
suraj          0       82    0         0       82    0

### Q95. Add margins (totals) in pivot tables.
> 💡 **Hint:** `margins=True, margins_name="TOTAL"` in `pivot_table()` adds a summary row and column.

In [ ]:
pd.pivot_table(df,values= 'scores', index = 'name', columns = 'city', aggfunc=["mean","max"], fill_value=0,margins= True, margins_name ='Total')

            mean                                max
city   bengalore khandala pune      Total bengalore khandala pune Total
name
ankit          0        0   98  98.000000         0        0   98  98.0
sanket        50        0    0  50.000000        50        0    0  50.0
suraj          0       82    0  82.000000         0       82    0  82.0
Total         50       82   98  76.666667        50       82   98  98.0

### Q96. Create multi-level pivot table.
> 💡 **Hint:** Pass lists to `index` and `columns` parameters: `index=["col1","col2"], columns=["col3"]`.

In [ ]:
pd.pivot_table(df,values= 'scores', index = ['name','class'], columns = 'city', aggfunc=["mean","max"], fill_value=0,margins= True, margins_name ='Total')

                  mean             max
city         bengalore Total bengalore Total
name   class
sanket 7.0          50  50.0        50  50.0
Total               50  50.0        50  50.0

### Q97. Convert DataFrame to pivot format.
> 💡 **Hint:** `df.pivot(index="row_key", columns="col_key", values="value")` — requires **unique** combinations of row/column keys (no aggregation).

In [ ]:
df.pivot(index="name", columns="scores", values="scores")

scores  NaN   50.0  82.0  98.0
name
ankit    NaN   NaN   NaN  98.0
antu     NaN   NaN   NaN   NaN
ganesh   NaN   NaN   NaN   NaN
pulkit   NaN   NaN   NaN   NaN
sanket   NaN  50.0   NaN   NaN
suraj    NaN   NaN  82.0   NaN

In [ ]:
df

   sr. no    name  class grade       city  scores
0       1   ankit    NaN     a       pune    98.0
1       2  pulkit   10.0     b     mumbai     NaN
2       3  sanket    7.0     c  bengalore    50.0
3       4  ganesh    8.0     d       pune     NaN
4       5   suraj    NaN     a   khandala    82.0
5       1    antu   10.0     a       pune     NaN

### Q98. Compare pivot vs groupby.
> 💡 **Hint:** `groupby()` is more flexible and returns a flat structure. `pivot_table()` gives a 2D grid and handles duplicates with aggregation. `pivot()` does **no aggregation** and fails on duplicates.

In [ ]:
data = {
    'Store': ['Store A', 'Store A', 'Store B', 'Store B'],
    'Fruit': ['Apple', 'Orange', 'Apple', 'Orange'],
    'Sales': [10, 15, 20, 25]
}

df5 = pd.DataFrame(data)
df5

     Store   Fruit  Sales
0  Store A   Apple     10
1  Store A  Orange     15
2  Store B   Apple     20
3  Store B  Orange     25

In [ ]:
df5.groupby('Fruit')['Sales'].sum()

Fruit
Apple     30
Orange    40
Name: Sales, dtype: int64

In [ ]:
df5.pivot_table(index='Store', columns='Fruit', values='Sales', aggfunc='sum')

Fruit    Apple  Orange
Store
Store A     10      15
Store B     20      25

In [ ]:
df5.pivot(index='Store', columns='Fruit', values='Sales') 
#fails on duplicates

Fruit    Apple  Orange
Store
Store A     10      15
Store B     20      25

### Q99. Build summary report using pivot table.
> 💡 **Hint:** Combine `pivot_table()` with `margins=True` and `fill_value=0`. Chain `.round(2)` for presentation. Export with `.to_csv()` or `.to_excel()`.

In [ ]:
pd.pivot_table(df,values= 'scores', index = ['name','class'], columns = 'city', aggfunc=["mean","max"], fill_value=0,margins= True, margins_name ='Total').round(2).to_csv('pivot_report.csv')

### Q100. Create an end-to-end analysis workflow.
> 💡 **Hint:** Follow this pipeline:  
> 1. Load data → 2. Inspect (shape, dtypes, nulls) → 3. Clean (fillna, drop_duplicates) → 4. Feature engineer → 5. GroupBy/pivot analysis → 6. Sort and rank → 7. Export results.

In [173]:
raw_data = {
    'Employee': ['Alice', 'Bob', 'Charlie', 'Alice', 'David', 'Eva', 'Bob'],
    'Department': ['HR', 'IT', 'IT', 'HR', 'Sales', 'Sales', 'IT'],
    'Salary': [50000, 60000, np.nan, 50000, 70000, 80000, 60000],
    'Performance_Score': [4.2, 3.8, 4.5, 4.2, 2.9, 4.7, 3.8]
}

df6 = pd.DataFrame(raw_data)

In [174]:
df6

  Employee Department   Salary  Performance_Score
0    Alice         HR  50000.0                4.2
1      Bob         IT  60000.0                3.8
2  Charlie         IT      NaN                4.5
3    Alice         HR  50000.0                4.2
4    David      Sales  70000.0                2.9
5      Eva      Sales  80000.0                4.7
6      Bob         IT  60000.0                3.8

In [177]:
#inspect

print("--- 1. Shape ---")
print(df6.shape)  # Output: (7, 4)

print("\n--- 2. Data Types ---")
print(df6.dtypes)

print("\n--- 3. Missing Values ---")
print(df6.isnull().sum())  # Shows 'Salary' has 1 missing value

--- 1. Shape ---
(7, 4)

--- 2. Data Types ---
Employee              object
Department            object
Salary               float64
Performance_Score    float64
dtype: object

--- 3. Missing Values ---
Employee             0
Department           0
Salary               1
Performance_Score    0
dtype: int64

In [ ]:
#Clean
# Drop duplicates (removes the duplicate Alice and Bob entries)
df6 = df6.drop_duplicates()

# Fill missing Salary with the column mean
mean_salary = df6['Salary'].mean()
df6['Salary'] = df6['Salary'].fillna(mean_salary)

C:\Users\abc\AppData\Local\Temp/ipykernel_19860/3506230472.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df6['Salary'] = df6['Salary'].fillna(mean_salary)

In [181]:
#Feature Engineer
# Bonus = 10% of salary if performance is above 4.0, otherwise 5%
df6['Bonus'] = np.where(df6['Performance_Score'] > 4.0, df6['Salary'] * 0.10, df6['Salary'] * 0.05)

C:\Users\abc\AppData\Local\Temp/ipykernel_19860/3717619751.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df6['Bonus'] = np.where(df6['Performance_Score'] > 4.0, df6['Salary'] * 0.10, df6['Salary'] * 0.05)

In [182]:
#GroupBy / Pivot Analysis
summary_df = df6.groupby('Department')[['Salary', 'Bonus']].sum()

In [183]:
#sort and Rank

# Sort descending
final_report = summary_df.sort_values(by='Bonus', ascending=False)

In [185]:
#export Result
final_report.to_csv('department_bonus_report.csv')
print("Workflow complete! File saved to your project directory.")

Workflow complete! File saved to your project directory.